# Generated by Django 5.0.4 on 2024-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
